os:
  - linux
  - osx
language: node_js
sudo: required
node_js:
- '8.13.0'
branches:
  only:
  - master
before_script:
  - npm install
script:
  - ./scripts/build.sh
#deploy:
#  provider: releases
#  api_key:
#    secure: a6264879868343cd51904bee868403cd1cfd6512
#  file: '*.tar.gz'
#  skip_cleanup: true
#  on:
#    repo: blockchain-desktop/hyperledger-fabric-desktop