os:
  - linux
  - osx
language: node_js
sudo: required
node_js:
- '8.13.0'
branches:
  only:
  - master
before_script:
  - npm install
script:
  - ./scripts/build.sh
deploy:
  provider: releases
  api_key:
    secure: ea18b7b5e25aa163f55df89f88f65606833194c3
  file: 'out/Fabric-Desktop-linux-x64.tar'
  skip_cleanup: true