peerGrpcUrl: grpc://localhost:7051
peerEventUrl: grpc://localhost:7053
ordererUrl: grpc://localhost:7050
mspId: Org1MSP
certificate: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
privateKey: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/cd96d5260ad4757551ed4a5a991e62130f8008a0bf996e4e4b84cd097a747fec_sk

